name: Daily POST Request to Hugging Face

on:
  schedule:
    - cron: '17 17 * * *'  # Runs daily at 0 AM UTC (2:00 AM in summer and 1:00 AM in winter croatian time)
  workflow_dispatch:      # Allows manual run from the Actions tab too

jobs:
  trigger_post:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request to Hugging Face Space and log response
        run: |
          RESPONSE=$(curl -s -X POST https://ritgptzsm-ritgptzsm.hf.space/sync)
          echo "Response from server:"
          echo "$RESPONSE"

