name: Daily POST Request to Hugging Face

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2 AM UTC
  workflow_dispatch:      # Allows manual run from the Actions tab too

jobs:
  trigger_post:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request to Hugging Face Space
        run: |
          curl -X POST http://127.0.0.1:8081/sync
